name: Deploy GitHub Pages
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y mkdocs-material
    - name: Build
      run: mkdocs build
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: site
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
